### ISSUE TITLE
Домашнее задание по Node

### ISSUE THREAD

**Issue by tiny-kottan** [KBoyarchuk/kottans-js-2016#9]
Complete https://gist.github.com/mkozhukharenko/74c2d55ff53f67670a6a7e1f0c37f1b0

**Comment by KBoyarchuk** [comment]
https://github.com/KBoyarchuk/kottans-js-2016/tree/master/week07/lec1

**Comment by mkozhukharenko** [comment]
looks good and it works :)

but, please, fix this:
`SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode`

**Comment by KBoyarchuk** [comment]
Bug fixed
